[rpc]
url="https://api.mainnet-beta.solana.com"

[bot_misc]
keypair_path="keypair.txt"
swap_threads=2
bind_ips=[
]
jito_bind_ips=[
]

[jupiter]
url="https://public.jupiterapi.com"
tips=[
    "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5",
    "HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe",
    "Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY",
    "ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49",
    "DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh",
    "ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt",
    "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL",
    "3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT"
]
delay=0.3 # secs

[[jito]]
enabled=true
url="https://mainnet.block-engine.jito.wtf"

[dynamic_mints]
url="https://tokens.jup.ag/tokens"
tags=[
    "birdeye-trending",
    "verified"
]
update_seconds=3600 # every hrs

[swap]
mint="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # USDC
decimal=6
min_spend=5
max_spend=40
min_gain=0.003
jito_static_tip_lamports=5000 # ~0.001 USDC
fetch_blockhash=10 # Secs

[close_account]
enabled=true
sol_min=0.05

